# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c8c9bf57e2a46801833dba420d413c44e1396aac739b7da6b9e0b3a4d5d6ce25ecb5d14a67d53a5f0b5653ca8de808a415760352aaaa0121dd06e88fa843af1c

test:
  secret_key_base: 2d7c81edc05db76d4696a3687dd895874ffdcf026baa72d3e1218cb7ab58d8f5ede03c87c13591a856f963c4bd14817e3a995b217f00b0b46cb3d465ec0e2cda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
